/*******************************************/
/*		Author	: Pola Magdy			   */
/*		Version	: V01					   */
/*		Date	: 6/11/2023			 	   */
/*     Description: DIO_Cfg.c		       */
/*******************************************/

#include "StdTypes.h"
#include "DIO_Interface.h"

const DIO_PinStatus_type DIO_PinsStatusArr[TOTAL_PINS]={
	
	OUTPUT50KHZ_PUSHPALL,			//PINA0
	OUTPUT50KHZ_PUSHPALL,			//PINA1
	OUTPUT50KHZ_AF_PUSHPALL,		//PINA2		Tx UART2
	INPUT_FLOATING  ,			//PINA3			Rx UART2
	INPUT_FLOATING,			//PINA4
	INPUT_FLOATING,			//PINA5
	INPUT_FLOATING,			//PINA6
	INPUT_FLOATING,			//PINA7
	INPUT_FLOATING,			//PINA8
	OUTPUT50KHZ_AF_PUSHPALL,		//PINA9		Tx UART1
	INPUT_FLOATING  ,				//PINA10	Rx UART1
	INPUT_FLOATING,			//PINA11
	INPUT_FLOATING,			//PINA12
	INPUT_FLOATING,			//PINA13
	INPUT_FLOATING,			//PINA14
	INPUT_FLOATING,			//PINA15
	INPUT_FLOATING,			//PINB0
	INPUT_FLOATING,			//PINB1
	INPUT_FLOATING,			//PINB2
	INPUT_FLOATING,			//PINB3
	INPUT_FLOATING,			//PINB4
	INPUT_FLOATING,			//PINB5
	INPUT_FLOATING,			//PINB6
	INPUT_FLOATING,			//PINB7
	INPUT_FLOATING,			//PINB8
	INPUT_FLOATING,			//PINB9
	OUTPUT50KHZ_AF_PUSHPALL,			//PINB10		Tx	UART3
	INPUT_FLOATING,			//PINB11				Rx		UART3
	INPUT_FLOATING,			//PINB12
	INPUT_FLOATING,			//PINB13
	INPUT_FLOATING,			//PINB14
	INPUT_FLOATING,			//PINB15
	INPUT_FLOATING,			//PINC0
	INPUT_FLOATING,			//PINC1
	INPUT_FLOATING,			//PINC2
	INPUT_FLOATING,			//PINC3
	INPUT_FLOATING,			//PINC4
	INPUT_FLOATING,			//PINC5
	INPUT_FLOATING,			//PINC6
	INPUT_FLOATING,			//PINC7
	INPUT_FLOATING,			//PINC8
	INPUT_FLOATING,			//PINC9
	INPUT_FLOATING,			//PINC10
	INPUT_FLOATING,			//PINC11
	INPUT_FLOATING,			//PINC12
	INPUT_FLOATING,			//PINC13
	INPUT_FLOATING,			//PINC14
	INPUT_FLOATING,			//PINC15
};
